/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pGUI_Ebene;

/**
 *
 * @author Andermann
 */
public class AnmeldePanel extends pGUI_Ebene.MittePanel {

    /**
     * Creates new form AnmeldePanel
     */
    public AnmeldePanel(HauptFenster haupt) {
        initComponents();
        verwaltung = new pFach_Ebene.AnmeldeVerwaltung();
        registrieren = new pFach_Ebene.Registrieren();
        hauptfenster = haupt;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Benutzerid = new javax.swing.JLabel();
        jLabel_Password = new javax.swing.JLabel();
        jTextField_Benutzerid = new javax.swing.JTextField();
        jPasswordField = new javax.swing.JPasswordField();
        jButton_Anmelden = new javax.swing.JButton();
        jButton_Registrieren = new javax.swing.JButton();
        jScrollPane = new javax.swing.JScrollPane();
        jTextArea_InfoAnmelden = new javax.swing.JTextArea();
        jTextField_ErrorMessage = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(400, 400));

        jLabel_Benutzerid.setText("Benutzer-ID:");

        jLabel_Password.setText("Password:");
        jLabel_Password.setMaximumSize(new java.awt.Dimension(62, 14));
        jLabel_Password.setMinimumSize(new java.awt.Dimension(62, 14));

        jTextField_Benutzerid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_BenutzeridActionPerformed(evt);
            }
        });

        jPasswordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldActionPerformed(evt);
            }
        });

        jButton_Anmelden.setText("Anmelden");
        jButton_Anmelden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnmeldenActionPerformed(evt);
            }
        });

        jButton_Registrieren.setText("Registrieren");
        jButton_Registrieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrierenActionPerformed(evt);
            }
        });

        jTextArea_InfoAnmelden.setEditable(false);
        jTextArea_InfoAnmelden.setColumns(20);
        jTextArea_InfoAnmelden.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jTextArea_InfoAnmelden.setRows(5);
        jTextArea_InfoAnmelden.setText("Melden sie sich mit ihren Benutzerdaten an.\nSollten sie noch keine Nutzerdaten haben, \nkönnen sie sich mit dem Registrierenbutton \neinen Benutzeraccount anlegen.");
        jTextArea_InfoAnmelden.setDisabledTextColor(new java.awt.Color(240, 240, 240));
        jScrollPane.setViewportView(jTextArea_InfoAnmelden);

        jTextField_ErrorMessage.setEditable(false);
        jTextField_ErrorMessage.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Benutzerid)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_Benutzerid, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton_Anmelden, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Registrieren, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTextField_ErrorMessage))
                    .addComponent(jScrollPane))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel_Benutzerid))
                    .addComponent(jTextField_Benutzerid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jButton_Anmelden)
                .addGap(18, 18, 18)
                .addComponent(jButton_Registrieren)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_ErrorMessage, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_BenutzeridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_BenutzeridActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_BenutzeridActionPerformed

    private void jButton_AnmeldenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnmeldenActionPerformed
        if(verwaltung.anmelden(jTextField_Benutzerid.getText(), String.valueOf(jPasswordField.getPassword())))
            hauptfenster.setPanel(1);
        else
            jTextField_ErrorMessage.setText("Überprüfen sie ihre Angaben!!!");
        
        
    }//GEN-LAST:event_jButton_AnmeldenActionPerformed

    private void jPasswordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldActionPerformed

    private void jButton_RegistrierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrierenActionPerformed
        hauptfenster.setPanel(2);
    }//GEN-LAST:event_jButton_RegistrierenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Anmelden;
    private javax.swing.JButton jButton_Registrieren;
    private javax.swing.JLabel jLabel_Benutzerid;
    private javax.swing.JLabel jLabel_Password;
    private javax.swing.JPasswordField jPasswordField;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTextArea jTextArea_InfoAnmelden;
    private javax.swing.JTextField jTextField_Benutzerid;
    private javax.swing.JTextField jTextField_ErrorMessage;
    // End of variables declaration//GEN-END:variables
// Variablen
    private pFach_Ebene.AnmeldeVerwaltung verwaltung;
    private pFach_Ebene.Registrieren registrieren;
    private pGUI_Ebene.HauptFenster hauptfenster;
}
