/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pGUI_Ebene;

import pFach_Ebene.Artikel;

/**
 *
 * @author Acer
 */
public class ArtikelPanel extends pGUI_Ebene.MittePanel {

    /**
     * Creates new form ArtikelPanel
     */
    public ArtikelPanel(HauptFenster haupt) {
        initComponents();
        hauptfenster = haupt;
    }
    
    public void setArtikel(long ID){
        Artikel a = hauptfenster.getArtikelverwaltung().getArtikel(ID);
        if(a != null){
            jLabel_Hersteller_Value.setText(a.getHersteller());
            jLabel_Modell_Value.setText(a.getModell());
            jLabel_Name_Value.setText(a.getName());
            jLabel_Preis_Value.setText("" + a.getPreis());
            Einzelpreis = a.getPreis();
            jSpinner_Anzahl.setValue(1);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_Warenkorb = new javax.swing.JButton();
        jSpinner_Anzahl = new javax.swing.JSpinner();
        jLabel_Hersteller = new javax.swing.JLabel();
        jLabel_Modell = new javax.swing.JLabel();
        jLabel_Preis = new javax.swing.JLabel();
        jLabel_Hersteller_Value = new javax.swing.JLabel();
        jLabel_Modell_Value = new javax.swing.JLabel();
        jLabel_Preis_Value = new javax.swing.JLabel();
        jLabel_Anzahl = new javax.swing.JLabel();
        jLabel_Artikelbild = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Name_Value = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));

        jButton_Warenkorb.setText("In den Warenkorb");

        jSpinner_Anzahl.setModel(new javax.swing.SpinnerNumberModel(1, 1, 99999, 1));
        jSpinner_Anzahl.setToolTipText("");
        jSpinner_Anzahl.setEditor(new javax.swing.JSpinner.NumberEditor(jSpinner_Anzahl, ""));
        jSpinner_Anzahl.setMaximumSize(new java.awt.Dimension(70, 25));
        jSpinner_Anzahl.setMinimumSize(new java.awt.Dimension(70, 25));
        jSpinner_Anzahl.setPreferredSize(new java.awt.Dimension(70, 25));
        jSpinner_Anzahl.setValue(1);
        jSpinner_Anzahl.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinner_AnzahlStateChanged(evt);
            }
        });

        jLabel_Hersteller.setText("Hersteller");
        jLabel_Hersteller.setMaximumSize(new java.awt.Dimension(60, 15));
        jLabel_Hersteller.setMinimumSize(new java.awt.Dimension(60, 15));
        jLabel_Hersteller.setPreferredSize(new java.awt.Dimension(60, 15));

        jLabel_Modell.setText("Modell");
        jLabel_Modell.setMaximumSize(new java.awt.Dimension(60, 15));
        jLabel_Modell.setMinimumSize(new java.awt.Dimension(60, 15));
        jLabel_Modell.setPreferredSize(new java.awt.Dimension(60, 15));

        jLabel_Preis.setText("Preis");
        jLabel_Preis.setMaximumSize(new java.awt.Dimension(60, 15));
        jLabel_Preis.setMinimumSize(new java.awt.Dimension(60, 15));
        jLabel_Preis.setPreferredSize(new java.awt.Dimension(60, 15));

        jLabel_Anzahl.setText("Anzahl");

        jLabel_Artikelbild.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pGUI_Ebene/Keks.jpg"))); // NOI18N
        jLabel_Artikelbild.setText("jLabel1");
        jLabel_Artikelbild.setMaximumSize(new java.awt.Dimension(380, 200));
        jLabel_Artikelbild.setMinimumSize(new java.awt.Dimension(380, 200));
        jLabel_Artikelbild.setPreferredSize(new java.awt.Dimension(380, 200));

        jLabel_Name.setText("Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Hersteller, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Modell, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Preis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Anzahl)
                            .addComponent(jLabel_Name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel_Hersteller_Value, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(jLabel_Modell_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel_Preis_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSpinner_Anzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Name_Value, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_Artikelbild, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(jButton_Warenkorb, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Name)
                    .addComponent(jLabel_Name_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Hersteller, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Hersteller_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Modell_Value, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel_Modell, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_Preis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_Preis_Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_Anzahl)
                    .addComponent(jSpinner_Anzahl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_Artikelbild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Warenkorb)
                .addGap(24, 24, 24))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinner_AnzahlStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinner_AnzahlStateChanged
        jLabel_Preis_Value.setText(""+ (double)((Math.round(((Einzelpreis * (int)jSpinner_Anzahl.getValue())*100))))/100);
    }//GEN-LAST:event_jSpinner_AnzahlStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Warenkorb;
    private javax.swing.JLabel jLabel_Anzahl;
    private javax.swing.JLabel jLabel_Artikelbild;
    private javax.swing.JLabel jLabel_Hersteller;
    private javax.swing.JLabel jLabel_Hersteller_Value;
    private javax.swing.JLabel jLabel_Modell;
    private javax.swing.JLabel jLabel_Modell_Value;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Name_Value;
    private javax.swing.JLabel jLabel_Preis;
    private javax.swing.JLabel jLabel_Preis_Value;
    private javax.swing.JSpinner jSpinner_Anzahl;
    // End of variables declaration//GEN-END:variables
    // Variablen
    private pGUI_Ebene.HauptFenster hauptfenster;
    private double Einzelpreis;
}
