/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pGUI_Ebene;

import java.util.*;
import javax.swing.text.Position;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import javax.swing.tree.TreeSelectionModel;
import pFach_Ebene.Artikel;

/**
 *
 * @author Andermann
 */
public class AuswahlPanel extends pGUI_Ebene.WestPanel {

    /**
     * Creates new form AuswahlPanel
     */
    public AuswahlPanel(HauptFenster haupt) {
        initComponents();
        hauptfenster = haupt;
        
       
    }
    
    public void addArtikel(pFach_Ebene.Artikel a) {
        DefaultMutableTreeNode root = (DefaultMutableTreeNode)jTree.getModel().getRoot();
        DefaultMutableTreeNode      parent;
        ArtikelNode neu = (ArtikelNode) root.getNextNode();
        while(neu != null){
            if(neu.getName().equals(a.getKategorie()) && neu.getID() == -1){
                neu.add(new ArtikelNode(a.getID(), a.getName()));
                return;
            }
            neu.getNextNode();
        }
        parent = new ArtikelNode(a.getKategorie());
        parent.add(new ArtikelNode(a.getID(), a.getName()));
        root.add(parent);
        jTree.updateUI();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wählen sie einen Artikel");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 50));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 50));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));

        jScrollPane.setMaximumSize(new java.awt.Dimension(200, 550));
        jScrollPane.setMinimumSize(new java.awt.Dimension(200, 550));
        jScrollPane.setPreferredSize(new java.awt.Dimension(200, 550));

        jTree.getSelectionModel().setSelectionMode
        (TreeSelectionModel.SINGLE_TREE_SELECTION);
        ArtikelNode root = new ArtikelNode("Artikel");
        jTree.setModel(new ArtikelModel(root));
        jTree.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTreeValueChanged(evt);
            }
        });
        jScrollPane.setViewportView(jTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTreeValueChanged
        ArtikelNode node = (ArtikelNode)
                           jTree.getLastSelectedPathComponent();
  
        // Wenn nichts gewählt zurück
        if (node == null) return;
       // Objekt holen wenn MittePanel == ArtikelPanel um die Auswahl
       // darzustellen
        if(hauptfenster.getMittePanel() instanceof ArtikelPanel){
           ArtikelPanel aPanel = (ArtikelPanel) hauptfenster.getMittePanel();
           aPanel.setArtikel(node.getID());
        }
        else
            return;
        
    }//GEN-LAST:event_jTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
    // Variablen
    private pGUI_Ebene.HauptFenster hauptfenster;
}
