/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pGUI_Ebene;

import pFach_Ebene.AnmeldeVerwaltung;
import pFach_Ebene.KundenVerwaltung;

/**+
 *
 * @author Andermann
 */
public class RegistrationsPanel extends pGUI_Ebene.MittePanel {

    /**
     * Creates new form RegistrationsPanel
     */
    public RegistrationsPanel(HauptFenster haupt) {
        initComponents();
        hauptfenster = haupt;
        anmeldeverwaltung = new AnmeldeVerwaltung();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_Strasse = new javax.swing.JLabel();
        jLabel_Benutzername = new javax.swing.JLabel();
        jLabel_Name = new javax.swing.JLabel();
        jLabel_Vorname = new javax.swing.JLabel();
        jLabel_NR = new javax.swing.JLabel();
        jButton_Registrieren = new javax.swing.JButton();
        jTextField_Vorname = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Strasse = new javax.swing.JTextField();
        jLabel_Passwort = new javax.swing.JLabel();
        jLabel_Passwort_wiederholen = new javax.swing.JLabel();
        jLabel_Kontonr = new javax.swing.JLabel();
        jTextField_Benutzername = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jTextField_Kontonr = new javax.swing.JTextField();
        jLabel_BLZ = new javax.swing.JLabel();
        jTextField_BLZ = new javax.swing.JTextField();
        jLabel_Kontoinhaber = new javax.swing.JLabel();
        jTextField_Kontoinhaber = new javax.swing.JTextField();
        jTextField_ErrorMessage = new javax.swing.JTextField();
        jTextField_NR = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(400, 400));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Strasse.setText("Straße");
        jLabel_Strasse.setMaximumSize(new java.awt.Dimension(60, 15));
        jLabel_Strasse.setMinimumSize(new java.awt.Dimension(60, 15));
        jLabel_Strasse.setPreferredSize(new java.awt.Dimension(60, 15));
        add(jLabel_Strasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 69, -1));

        jLabel_Benutzername.setFont(jLabel_Benutzername.getFont());
        jLabel_Benutzername.setText("Benutzername");
        add(jLabel_Benutzername, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jLabel_Name.setFont(jLabel_Name.getFont());
        jLabel_Name.setText("Name");
        jLabel_Name.setMaximumSize(new java.awt.Dimension(60, 15));
        jLabel_Name.setMinimumSize(new java.awt.Dimension(60, 15));
        jLabel_Name.setPreferredSize(new java.awt.Dimension(60, 15));
        add(jLabel_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 69, -1));

        jLabel_Vorname.setText("Vorname");
        jLabel_Vorname.setMaximumSize(new java.awt.Dimension(60, 15));
        jLabel_Vorname.setMinimumSize(new java.awt.Dimension(60, 15));
        jLabel_Vorname.setPreferredSize(new java.awt.Dimension(60, 15));
        add(jLabel_Vorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 69, -1));

        jLabel_NR.setText("Nr.");
        add(jLabel_NR, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 100, 22, -1));

        jButton_Registrieren.setText("Registrieren");
        jButton_Registrieren.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RegistrierenActionPerformed(evt);
            }
        });
        add(jButton_Registrieren, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 352, 190, -1));

        jTextField_Vorname.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_Vorname, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 59, 111, -1));

        jTextField_Name.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 21, 111, -1));

        jTextField_Strasse.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_Strasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 97, 111, -1));

        jLabel_Passwort.setText("Passwort");
        add(jLabel_Passwort, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 69, -1));

        jLabel_Passwort_wiederholen.setText("Passwort");
        add(jLabel_Passwort_wiederholen, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 69, -1));

        jLabel_Kontonr.setText("Kontonr");
        add(jLabel_Kontonr, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 69, -1));

        jTextField_Benutzername.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_Benutzername, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 111, -1));

        jPasswordField1.setMaximumSize(new java.awt.Dimension(111, 20));
        jPasswordField1.setMinimumSize(new java.awt.Dimension(111, 20));
        add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 173, 110, -1));

        jPasswordField2.setMaximumSize(new java.awt.Dimension(111, 20));
        jPasswordField2.setMinimumSize(new java.awt.Dimension(111, 20));
        add(jPasswordField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 211, 110, -1));

        jTextField_Kontonr.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_Kontonr, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 249, 111, -1));

        jLabel_BLZ.setText("BLZ");
        add(jLabel_BLZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(239, 252, 22, -1));

        jTextField_BLZ.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_BLZ, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 249, 100, -1));

        jLabel_Kontoinhaber.setText("Inhaber");
        add(jLabel_Kontoinhaber, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 69, -1));

        jTextField_Kontoinhaber.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_Kontoinhaber, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 287, 111, -1));

        jTextField_ErrorMessage.setEditable(false);
        jTextField_ErrorMessage.setMaximumSize(new java.awt.Dimension(6, 20));
        add(jTextField_ErrorMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 321, 400, -1));
        add(jTextField_NR, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 97, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_RegistrierenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RegistrierenActionPerformed
        if((String.valueOf(jPasswordField1.getPassword())).equals(
           (String.valueOf(jPasswordField2.getPassword())))){
            anmeldeverwaltung.registrieren(jTextField_BLZ.getText(), 
                                     jTextField_Benutzername.getText(), 
                                     jTextField_Kontoinhaber.getText(), 
                                     jTextField_Kontonr.getText(), 
                                     jTextField_NR.getText(), 
                                     jTextField_Name.getText(), 
                                     String.valueOf(jPasswordField1.getPassword()), 
                                     jTextField_Strasse.getText(), 
                                     jTextField_Vorname.getText());
            pGUI_Ebene.AnmeldePopUp t = new AnmeldePopUp();
            t.setLocationRelativeTo(this);
            t.setVisible(true);
            hauptfenster.setPanel(1);
        }
        else
            jTextField_ErrorMessage.setText("Password muss übereinstimmen");
    }//GEN-LAST:event_jButton_RegistrierenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Registrieren;
    private javax.swing.JLabel jLabel_BLZ;
    private javax.swing.JLabel jLabel_Benutzername;
    private javax.swing.JLabel jLabel_Kontoinhaber;
    private javax.swing.JLabel jLabel_Kontonr;
    private javax.swing.JLabel jLabel_NR;
    private javax.swing.JLabel jLabel_Name;
    private javax.swing.JLabel jLabel_Passwort;
    private javax.swing.JLabel jLabel_Passwort_wiederholen;
    private javax.swing.JLabel jLabel_Strasse;
    private javax.swing.JLabel jLabel_Vorname;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JTextField jTextField_BLZ;
    private javax.swing.JTextField jTextField_Benutzername;
    private javax.swing.JTextField jTextField_ErrorMessage;
    private javax.swing.JTextField jTextField_Kontoinhaber;
    private javax.swing.JTextField jTextField_Kontonr;
    private javax.swing.JTextField jTextField_NR;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Strasse;
    private javax.swing.JTextField jTextField_Vorname;
    // End of variables declaration//GEN-END:variables
    // Variablen
    private pGUI_Ebene.HauptFenster hauptfenster;
    private pFach_Ebene.AnmeldeVerwaltung anmeldeverwaltung;
}
