/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pGUI_Ebene;

import javax.swing.tree.TreeSelectionModel;

/**
 *
 * @author Andermann
 */
public class WarenkorbPanel extends pGUI_Ebene.OstJPanel {

    /**
     * Creates new form WarenkorbPanel
     */
    public WarenkorbPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane_Artikelauswahl = new javax.swing.JScrollPane();
        jTree = new javax.swing.JTree();
        JButton_Remove = new javax.swing.JButton();
        JLabel_Warenkorb = new javax.swing.JLabel();
        jButton_Kaufen = new javax.swing.JButton();
        jScrollPane_Betrag = new javax.swing.JScrollPane();
        jTextArea_Betrag = new javax.swing.JTextArea();

        setMaximumSize(new java.awt.Dimension(200, 600));

        jScrollPane_Artikelauswahl.setMaximumSize(new java.awt.Dimension(200, 322));

        jTree.setMaximumSize(new java.awt.Dimension(200, 322));
        jTree.getSelectionModel().setSelectionMode
        (TreeSelectionModel.SINGLE_TREE_SELECTION);
        ArtikelNode root = new ArtikelNode("Artikel");
        jTree.setModel(new ArtikelModel(root));
        jTree.setMaximumSize(new java.awt.Dimension(200, 322));
        jScrollPane_Artikelauswahl.setViewportView(jTree);

        JButton_Remove.setText("Entfernen");

        JLabel_Warenkorb.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        JLabel_Warenkorb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabel_Warenkorb.setText("Warenkorb");
        JLabel_Warenkorb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JLabel_Warenkorb.setMaximumSize(new java.awt.Dimension(200, 50));
        JLabel_Warenkorb.setMinimumSize(new java.awt.Dimension(200, 50));
        JLabel_Warenkorb.setPreferredSize(new java.awt.Dimension(200, 50));

        jButton_Kaufen.setText("Kaufen");

        jScrollPane_Betrag.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTextArea_Betrag.setEditable(false);
        jTextArea_Betrag.setColumns(20);
        jTextArea_Betrag.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jTextArea_Betrag.setRows(5);
        jTextArea_Betrag.setText("Colors : 120.05$\nSports : 300.20$\nFood   :  82.50$\n------------------------\nBetrag : 502.75$");
        jTextArea_Betrag.setMaximumSize(new java.awt.Dimension(200, 144));
        jTextArea_Betrag.setMinimumSize(new java.awt.Dimension(200, 144));
        jScrollPane_Betrag.setViewportView(jTextArea_Betrag);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLabel_Warenkorb, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jScrollPane_Artikelauswahl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane_Betrag, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
            .addComponent(jButton_Kaufen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JButton_Remove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JLabel_Warenkorb, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Artikelauswahl, javax.swing.GroupLayout.PREFERRED_SIZE, 322, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane_Betrag, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Kaufen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JButton_Remove)
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Remove;
    private javax.swing.JLabel JLabel_Warenkorb;
    private javax.swing.JButton jButton_Kaufen;
    private javax.swing.JScrollPane jScrollPane_Artikelauswahl;
    private javax.swing.JScrollPane jScrollPane_Betrag;
    private javax.swing.JTextArea jTextArea_Betrag;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables
}
